### ISSUE TITLE
The about us page picture is not visible

### ISSUE THREAD

**Issue by tenzintsongi** [Adityaarai/VROOM-Car-Rental#104]

**Comment by Abrahamhyolmo** [comment]
![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119650143/0aa880de-b00a-4abf-afb2-398731c2d796)
i have fix the picture not showing by making some changes in code
 </div>
      <div class="hero-image">
        <img src="{% static 'img/abtUs.jpg' %}">
      </div>
