### ISSUE TITLE
Details of developer team is not visible while hovering the box in "About Us" Page

### ISSUE THREAD

**Issue by tenzintsongi** [Adityaarai/VROOM-Car-Rental#106]
While hovering the developer team's details in "About Us" page, the text cannot be seen because the hovering effect's dark color fills the text's box

**Comment by Abrahamhyolmo** [comment]
i have changed the color and made it more visible
 .profile-box:hover {
    background-color: #97b7c9;
  }
![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119650143/e38cbc43-de5f-4d08-b3ff-46587a322b58)
