### ISSUE TITLE
CSS issue in Distributor's dashboard

### ISSUE THREAD

**Issue by tenzintsongi** [Adityaarai/VROOM-Car-Rental#107]
When the distributor logs into their dashboard, some text appears outside the designated box.
![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119144229/d7557064-fc87-460f-ade1-1f564bd71025)

**Comment by Krishantamang** [comment]
![Screenshot 2024-05-18 004713](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119145078/cf85ab67-9c3c-469a-a9b6-2cf87c1f9e93)
I have fixed the CSS to make the information inside the card.
