### ISSUE TITLE
CSS Problem in Distributor's Dashboard Booking Section

### ISSUE THREAD

**Issue by tenzintsongi** [Adityaarai/VROOM-Car-Rental#110]
![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119144229/878c6d27-b2b5-4609-ba06-eedadbca4efc)
The navigation bar's CSS is not covering the entire page, causing misalignment with text; one element is on the left, and another is on the right.

**Comment by Krishantamang** [comment]
![Screenshot 2024-05-18 004751](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119145078/5542cdf4-053e-4175-9de0-3eb28648e768)
I have fixed the CSS of Booking section so the content does align properly.
