### ISSUE TITLE
CSS problem when distributor deletes the car from cars section

### ISSUE THREAD

**Issue by tenzintsongi** [Adityaarai/VROOM-Car-Rental#111]
![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119144229/ca50d805-09f1-4394-9219-53c32a01b213)
When distributor deletes the car from the cars section, the deletion successful message is not shown properly.

**Comment by Krishantamang** [comment]
![Screenshot 2024-05-18 004803](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119145078/c7840655-8003-4980-b089-dc82bfcbdc50)
I have fixed it to be seen properly.
