### ISSUE TITLE
Added new feature

### ISSUE THREAD

**Issue by tenzintsongi** [Adityaarai/VROOM-Car-Rental#118]
As a customer, I want to pre-book a vehicle in the rental system so that I can ensure availability and streamline the process of renting a vehicle for my desired dates and times.

**Comment by Nileena106** [comment]
For adding that feature, in the frontend code of 'car_details.html', through where the 'Book Cars' details is shown. I added the following code, it will check if the availability of car is 'Booked' or 'Available' in the database. If it is booked, then it shows the message and pre-booking date based on the end-date of that booked car order. That date will be fetched from CarOrder model database. 

![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/118924024/e4ed5620-f554-4523-a661-37f54d8f60b5)
