### ISSUE TITLE
Shows validation error when customer books the car without adding start date and end date.

### ISSUE THREAD

**Issue by tenzintsongi** [Adityaarai/VROOM-Car-Rental#45]
![image_2024-05-10_224529563](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119144229/f0a39199-ac4f-4b5b-9169-e81c3267a589)

**Comment by Adityaarai** [comment]
The issue was created when null value was sent in the post method of the booking form. It was solved by adding some simple error handling.
![image_2024-05-12_015438160](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119116034/66e49976-0f39-47be-a9ee-b66b084f5c9e)
