### ISSUE TITLE
Error page when booking without login

### ISSUE THREAD

**Issue by tenzintsongi** [Adityaarai/VROOM-Car-Rental#46]
Shows error when customer books the car without login

![324680728-74615046-7c1e-41ee-ba4b-b363fb2b8ec4](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119144229/e0ca9f7e-f32a-4d89-937e-1976eb8dce9a)

**Comment by Adityaarai** [comment]
This issue was raised due to the sign in function being incorrect in the index view. This was fixed easily by replacing the previous code with the correct code.

Correct Code
![Uploading image.png…]()
