### ISSUE TITLE
Booking request CSS

### ISSUE THREAD

**Issue by tenzintsongi** [Adityaarai/VROOM-Car-Rental#59]
![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119144229/def55a58-47fd-4ad7-8491-bb0f36c2eda1)

The booking request CSS needs improvement as it currently falls short of expected standards.

**Comment by Krishantamang** [comment]
![Screenshot 2024-05-15 001355](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119145078/c848ea6b-bf84-4517-befe-502bc99547e4)
The CSS has been fixed.
