### ISSUE TITLE
Issues with Car Details CSS

### ISSUE THREAD

**Issue by tenzintsongi** [Adityaarai/VROOM-Car-Rental#60]
![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119144229/bcaf69ed-e98d-461f-82e7-e9310c06b5f8)
The way we show car details using CSS isn't as polished as it could be. We need to work on it to make it look better.

**Comment by Krishantamang** [comment]
![Screenshot 2024-05-18 222030](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119145078/08815b54-4a83-4497-91e7-97b3320ade1e)
I fixed this.
