### ISSUE TITLE
Admin Dashboard's button not working

### ISSUE THREAD

**Issue by tenzintsongi** [Adityaarai/VROOM-Car-Rental#80]
![440893310_2481894182199270_7102294401661859963_n](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119144229/c3bcb92f-7c84-4939-bae0-62a7279d922a)
On the left side of the dashboard there are three buttons, when admin clicks the button it shows an error.

**Comment by Krishantamang** [comment]
I have fixed the dashboard buttons.
