### ISSUE TITLE
Booking car issue 

### ISSUE THREAD

**Issue by PrajwolGithub** [Adityaarai/VROOM-Car-Rental#85]
![image_2024-05-16_112355649](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119144331/7d492e1d-c3fc-4eb0-be8d-91477825c8bf)
FieldError is thrown after choosing the start and end dates of the booking and pressing the book button.

**Comment by Adityaarai** [comment]
This issue was raised due to the recent change in the database. Previously the rentee's email was used to show the user in car order but after the whole instance of the user was added in the Car Order table. So, this issue was resolved very easily by changing the updated variables in the code.
