### ISSUE TITLE
Pre booking layout 

### ISSUE THREAD

**Issue by PrajwolGithub** [Adityaarai/VROOM-Car-Rental#91]
![image_2024-05-16_224121162](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119144331/26ddf7c0-62c4-45b2-acad-b8a0c2bf33ab)
The padding is not correct, and also display it above the Categories panel.

**Comment by Krishantamang** [comment]
![Screenshot 2024-05-17 002420](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119145078/4a3e0f24-b68e-4a37-8d9c-59f8645cd5a9)
![Screenshot 2024-05-17 002431](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119145078/7c21e476-790c-4080-8439-4cde9cbbe5b1)
I have removed the pre booking from the landing page and added it to the car listing section.

**Comment by PrajwolGithub** [comment]
Thank you
