### ISSUE TITLE
Error Page When Booking the car

### ISSUE THREAD

**Issue by tenzintsongi** [Adityaarai/VROOM-Car-Rental#94]
![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119144229/d33b69ec-a43f-4516-93f6-9963889a3f42)
After filling the start date and end date, when user clicks the "Book" button it shows an error

**Comment by Adityaarai** [comment]
This issue was raised due to the recent change in the database. Previously the rentee's email was used to show the user in car order but after the whole instance of the user was added in the Car Order table. So, this issue was resolved very easily by changing the updated variables in the code.
