### ISSUE TITLE
Learn more button not working

### ISSUE THREAD

**Issue by PrajwolGithub** [Adityaarai/VROOM-Car-Rental#96]
![image_2024-05-17_135810615](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119144331/bdb87d5d-b4b6-4ccc-b9c3-91fa42fded55)
learn more button on about us page does not work

**Comment by Abrahamhyolmo** [comment]
![Screenshot 2024-05-18 223737](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119650143/6d547afc-16a8-4649-830a-14cb41fe5590)

i have made the learn more  page working
